### PR TITLE
Add svg fingerprinting

### PR DESCRIPTION
**Pull request by amyrlam**
## :pushpin: Summary

Ref: https://cli.emberjs.com/release/advanced-use/asset-compilation/#fingerprintingandcdnurls

Touches on a few overlapping issues related to the sprite and caching (browser and CDN)

## :camera_flash: Screenshots

WAS:
image

IS:
image

### CODE REVIEW

**Comment by didoo** [comment]
@amyrlam I don't know enough of the technicalities of Ember to fully understand the implications of these changes. is better if @Dhaulagiri approves it

**Comment by amyrlam** [comment]
ok sg, closing

**Comment by MelSumner** [comment]
@amyrlam  Apologies for the delay in reviewing this; I've been meaning to review how fingerprinting works with `fastboot` and/or `prember`. I had a red flag in my mind that one or both of these needs fingerprinting to be turned off.

**Comment by amyrlam** [comment]
there's https://github.com/hashicorp/design-system-playground-fastboot or `terraform-registry` uses fastboot if you want to give their dev env a try. (it's a bit of a slog, i haven't finished it, but greg hoin can help if get stuck)

TBH not sure about `prember` at hashi though

**Pull request closed without merging**
