### PR TITLE
Tweak instructions

### PR DESCRIPTION
**Pull request by amyrlam**
## :pushpin: Summary

Following up from the meeting, what do you think about this change? Not super important, just a suggestion

I added the console.log back, but wasn't sure if there was a reason it was commented out?

### CODE REVIEW

**Review by MelSumner — APPROVED** [review]
👍

**Review by heatherlarsen — APPROVED** [review]
lgtm 👍

**Comment by amyrlam** [comment]
i'll merge in and if didoo has changes tmrw will fix in a follow-on!

**Comment by didoo** [comment]
@amyrlam I'm ok with the changes (only the console.log, are you sure? it adds a lot of noise :) in any case we can comment it later, so all good for me)

**Comment by amyrlam** [comment]
good pt, how about https://github.com/hashicorp/flight/pull/259? tagged you there as reviewer

**Pull request merged**
