### PR TITLE
Bump packages

### PR DESCRIPTION
**Pull request by amyrlam**
## :pushpin: Summary

I'm going to run a quick test in external app to make sure this package works - it works!
- Ran a `yarn release` in `flight-icons/` and `ember-flight-icons/`
- Note: We publish to npm before committing to GitHub

Testing:
- flight-icons: https://github.com/hashicorp/boundary-ui/pull/761 can see namespace change `flight-icons/svg`
  - [ ] TODO: we should let marketing know as well (kendallstrautmanand jmfury) but let's see if this namespacing is cool with Boundary first 
- ember-flight-icons: https://github.com/hashicorp/design-system-playground/pull/5

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
> Note: We publish to npm before committing to GitHub

As part of the experimentation or was the thinking that this was the order of operations moving forward?

**Review by Dhaulagiri — APPROVED** [review]

**Comment by didoo** [comment]
> As part of the experimentation or was the thinking that this was the order of operations moving forward?

Depends on what we want to do, how much we want to automate the process. Maybe we can try a few times (next time you could do a release, so you can see the whole flow) and then we can decide what is better.

**Comment by amyrlam** [comment]
+1 

To use the tools that have you pick the # via CLI, the publish comes first. We can go back to how it was done manually before (submit PR, have it merged to main, then run a `npm publish`) ... but then there's not much reason to use the tool AFAICT?

For beta release, seems like the tool doesn't like the format of this version # `0.0.9-beta`. I would suggest we make the next release `0.0.10-beta.0` ... and then do future beta's as a `0.0.10-beta.0` ... but maybe we'll just be at a 1.0 then? ref: https://kevinkreuzer.medium.com/publishing-a-beta-or-alpha-version-to-npm-46035b630dd7

We can also deprecate all the beta versions in npm once we hit a 1.0, once Boundary and Marketing folks are on 1.0.

**Comment by amyrlam** [comment]
I'll merge this in for now but def happy to continue the convo. Cristiano needs to be added to HashiCorp npm, issue with personal/work email. I had just changed my account to work email cause don't really publish npm packages elsewhere

Let's have Brian or Melanie do the next npm bump, and can test out the instructions (some docs tweaks are coming from Cristiano)

**Comment by didoo** [comment]
> +1
> 
> To use the tools that have you pick the # via CLI, the publish comes first. We can go back to how it was done manually before (submit PR, have it merged to main, then run a `npm publish`) ... but then there's not much reason to use the tool AFAICT?
> 
> For beta release, seems like the tool doesn't like the format of this version # `0.0.9-beta`. I would suggest we make the next release `0.0.10-beta.0` ... and then do future beta's as a `0.0.10-beta.0` ... but maybe we'll just be at a 1.0 then?
Maybe we just publish a `1.0.0-rc` (release candidate?). Anyway, once you get used to the `bump` tool, it's pretty straightforward to use.

> We can also deprecate all the beta versions in npm once we hit a 1.0, once Boundary and Marketing folks are on 1.0.
+1

**Comment by amyrlam** [comment]
👍 `1.0.0-rc sgtm`

**Pull request merged**
