### PR TITLE
Update template to mention why failing tests

### PR DESCRIPTION
**Pull request by amyrlam**
## :pushpin: Summary

Provide a better DX

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
This seems expedient, but I also think it might be worth evaluating whether or not we actually need to test against canary or the embroider setup given we are unlikely to want to invest time into fixing a failure that only happens against canary for example.

**Review by MelSumner — APPROVED** [review]
suggestion (non-blocking): I wouldn't mind it if we took those test scenarios out of our ember-try setup.

**Comment by amyrlam** [comment]
seems like could merge in https://github.com/hashicorp/flight/pull/96, instead of this PR

**Comment by amyrlam** [comment]
closing in favor of https://github.com/hashicorp/flight/pull/96

**Pull request closed without merging**
