### PR TITLE
Regenerate assets after splitting between “mono” and “color” icons in Figma

### LINKED ISSUE #185: Fix how colored icons are shown in the miniwebsite
In #179 we've added the newly generated SVGs to the mini-website. They now contain also the colored icons, but for some reasons the mini website is using the mono icons also for the colored ones. See screenshot below:

screenshot_67

### PR DESCRIPTION
**Pull request by didoo**
## :pushpin: Summary

This should fix #185 and avoid us to change the API of the `FigmaIcon` component to support "tinted" icons (now the icon "name" contains an extra `-color` suffix when is colored, so effectively is a distinct icon, not a variant.

Please @Dhaulagiri can you check if this fix #185? thanks

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
This seems to mostly have fixed the problem with the exception of `azure-devops-color` which I can investigate tomorrow

**Comment by didoo** [comment]
the issue with the `azure-devops-color` icon is that there are conflicting IDs in the sprite (probably the `npx spritesh` command doesn't take in account this). In any case the SVGs are automatically copied now in #171 so probably we can close this one, and later check in #171 that the icons are rendered correctly in the mini-website.

**Review by Dhaulagiri — APPROVED** [review]
I don't see the conflicting IDs but I'm happy to revisit if it's still a problem with the sprite after it's generated via the build.

**Comment by didoo** [comment]
@Dhaulagiri for future reference: the `paint0_linear` ID is not unique in the sprite:
screenshot_76
screenshot_75

**Pull request merged**
