### PR TITLE
Remove local linking from ember-flight-icons

### PR DESCRIPTION
**Pull request by amyrlam**
## :pushpin: Summary

We are publishing beta npm addons now, which is less confusing

cherry-picked from https://github.com/hashicorp/flight/pull/119

### :speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

Examples: 
- issue (ux,non-blocking): These buttons should be red, but let's handle this in a follow-up.
- suggestion (non-blocking): Let's change this wording to make it easier to understand.
- issue (blocking): We shouldn't introduce this kind of tech debt; let's pair and resolve the issue in a more sustainable way.

### CODE REVIEW

**Review by Dhaulagiri — APPROVED** [review]
🤷‍♂️  I think knowing this is possible still has value as someone _may_ want to play with the addon locally in their app, but I also think knowing how to do this with a published package might be/is common knowledge?

**Review by MelSumner — APPROVED** [review]
Totally fine with this change, but we should get folks up to speed on using `yarn link`, so it's not confusing. As an addon developer, I use this a lot- I can't imagine having to wait to have an npm package published first. That would really slow me down a lot.

**Comment by amyrlam** [comment]
makes sense, how about we leave it in then and i close this PR? i'm about to update the contributing for both anyways

**Comment by amyrlam** [comment]
it personally took a long time for me to get ^^ working correctly. maybe it just seemed easier in npm elsewhere, not exactly sure. i was making the change more for pushing folks to use the addon / decouple it from https://github.com/hashicorp/flight/pull/119

so closing it sgtm, if no objections

**Comment by MelSumner** [comment]
I don't think we should close it, I think we should merge it; I'm saying as a meta issue, we should all get comfortable using `yarn link` or `npm link` because as addon devs we'll likely use it quite often.

**Comment by amyrlam** [comment]
gotcha. ok, well i'm not fluent in it, so seems like keeping the instructions up there doesn't hurt? i'll close it for now and make another PR updating both CONTRIBUTING's which relates to heather's RFC. hope this is an ok step forward

**Pull request closed without merging**
