### PR TITLE
Add npm badge to README

### PR DESCRIPTION
**Pull request by amyrlam**
## :pushpin: Summary

I am using this PR as a way to show our Vercel setup working. Figured would add the npm badge as a mergeable example.

Once this merged, or anything else is merged to `main`, we should be able to see https://flight-rho.vercel.app/ working.

## :link: External Links

Vercel setup: https://vercel.com/hashicorp/flight/settings/domains
Resolves: https://github.com/hashicorp/flight/issues/53

### CODE REVIEW

**Comment by amyrlam** [comment]
@hashicorp/design-systems you can see the preview on each PR now, click "Preview" link above. However, keep in mind that right now the Go export and the `ember-flight-icons/` dir are not synced yet, but 🔜

**Comment by amyrlam** [comment]
note: flight.vercel.app is taken. 

i changed it from https://flight-rho.vercel.app/ to https://flight-staging.vercel.app/. we can change it again. just mentioning in case folks want to voice their naming thoughts re: today's naming discussion

**Review by MelSumner — APPROVED** [review]
Thank you for adding this.

**Comment by amyrlam** [comment]
the tests didn't run? let's merge and if the tests are not running on main, i can fix it

**Pull request merged**
