### PR TITLE
sync/build new marketing icons

### PR DESCRIPTION
**Pull request by Dhaulagiri**
## :pushpin: Summary

Addresses https://github.com/hashicorp/flight/issues/283

## :building_construction: How to Build and Test the Change

~~Spot check new/updated icons in the preview app~~ Does not actually work until we release a new package

Look at the icons in the files changed tab

### :speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

Examples: 
- issue (ux,non-blocking): These buttons should be red, but let's handle this in a follow-up.
- suggestion (non-blocking): Let's change this wording to make it easier to understand.
- issue (blocking): We shouldn't introduce this kind of tech debt; let's pair and resolve the issue in a more sustainable way.

### CODE REVIEW

**Comment by didoo** [comment]
@amyrlam any news/updates on #286 / #287 ? we have a few icons that changed path but is kinda unexpected (it can be just Figma) so having a visual regression test before/after may help to do the comparison

**Comment by Dhaulagiri** [comment]
> so having a visual regression test before/after may help to do the comparison

A realization I had doing this PR is that preview app now only  shows what is in the actual published package (the ember addon relies on `@hashicorp/flight-icons` vs previously having the sprite manually copied in), so they can't be used to see changes like this which is a suboptimal unintended side effect of that change I think 🤔

**Comment by Dhaulagiri** [comment]
Although the intention of the Percy tests was to exercise the behavior of the ember component, not necessarily the individual icons themselves

**Comment by amyrlam** [comment]
yeah, not sure. i think it was fine how it was before where this PR would trigger percy, but no preference. it doesn't even work rn.

as for percy, no update. cristiano - added you to the chain with their support. just pinged a friend there to see if can help as the support time has been very long rn 
- i didn't finish debugging but can use https://github.com/hashicorp/flight/pull/261 or the other PR's again, there were some weird things happening... could def spend more time on it.

**Review by didoo — APPROVED** [review]

**Pull request merged**
